### ISSUE TITLE
Question: Does this work with jsx ?

### ISSUE THREAD

**Issue by christopherbalz** [6to5/6to5-jest#4]
Tried adding `"moduleFileExtensions": ["js", "json", "es6", "jsx"],` but that doesn't work.

**Comment by sebmck** [comment]
Can you please elaborate? I'm not sure what you mean.

**Comment by christopherbalz** [comment]
The plug-in does not seem to me to process jsx files.

**Comment by sebmck** [comment]
Having `"moduleFileExtensions": ["js", "json", "es6", "jsx"]` in the jest part of your `package.json` should tell jest to preprocess all those extensions through the defined preprocessor. Might be a possible jest issue, I'm not very familiar with it.

**Comment by christopherbalz** [comment]
I had 'jsx' in that list, but got an error indicating breakage on the jsx syntax.  My base set-up works with jsx.

**Comment by sebmck** [comment]
@christopherbalz Ah, I think I found out what's causing this. I've pushed out a new 6to5 version 2.12.1. Can you try reinstalling `6to5-jest`? It should automatically update to the latest 6to5.

**Comment by christopherbalz** [comment]
Great, thanks!  I changed my configuration all around to use a preprocessor that pipes `React.transform` "harmony"'d code into Traceur, but if I get a chance I will definitely try it!
