### ISSUE TITLE
Use 6to5-core instead of 6to5

### ISSUE THREAD

**Issue by hawkrives** [6to5/6to5-jest#6]
Unless Jest needs the full power of 6to5, I think this package could also depend on 6to5-core.

I'll know shortly, once I write some tests for my React components.

Cheers! :beers: And thanks, as always, for this whole library.

**Comment by sebmck** [comment]
Sure, I haven't gotten around to migrating all the plugins to use `6to5-core` so I've really only been doing it as it's been requested/bought up. Released as 1.0.1.

**Comment by hawkrives** [comment]
uh... did I lose a few minutes somewhere?

**Comment by hawkrives** [comment]
No problem!

**Comment by hawkrives** [comment]
And, *dang*, you're fast!
